export default {
    border: true,
    size: "large",
    showSelection: true,
    showIndex: true,
    isShowFooter: true,
    propList: [
        { prop: "name", label: "商品名称", minWidth: "100", align: "center" },
        { prop: "oldPrice", label: "原价格", minWidth: "80", align: "center" },
        { prop: "newPrice", label: "新价格", minWidth: "80", align: "center" },
        { prop: "desc", label: "商品描述", minWidth: "100", align: "center" },
        { prop: "status", label: "状态", minWidth: "80", align: "center", slotName: "status" },
        {
            prop: "imgUrl",
            label: "图片",
            minWidth: "100",
            slotName: "image",
            align: "center",
        },
        { prop: "inventoryCount", label: "库存", minWidth: "80", align: "center" },
        { prop: "saleCount", label: "销量", minWidth: "80", align: "center" },
        { prop: "favorCount", label: "收藏", minWidth: "80", align: "center" },
        { prop: "address", label: "地址", minWidth: "80", align: "center" },
        {
            prop: "createAt",
            label: "创建时间",
            minWidth: "220",
            slotName: "createAt",
            align: "center",
        },
        {
            prop: "updateAt",
            label: "更新时间",
            minWidth: "220",
            slotName: "updateAt",
            align: "center",
        },
        {
            prop: "operations",
            label: "操作",
            minWidth: "150",
            slotName: "operations",
            align: "center",
        },
    ],
};
